"""Tool registry — all 25 v1.0 tools with full metadata."""
from __future__ import annotations
import hashlib
import json
from pacca.models.tool_metadata import ToolMetadata, RiskLevel

ALL_PLATFORMS = ["darwin", "win32", "linux"]

_REGISTRY_DATA = [
    ToolMetadata(
        name="list_directory",
        description="List contents of a directory",
        risk_level=RiskLevel.LOW, reversible=True, reversible_notes=None,
        requires_confirmation=False, conditional_confirmation_rules=[],
        data_egress=False, egress_type="none", network_behavior=None,
        path_scope_required=True, max_files_without_confirmation=None,
        max_total_bytes_without_confirmation=None, overwrite_policy="allow",
        secret_scan_required=False, requires_diff_preview=False,
        dry_run_supported=True, undo_supported=False, atomic=True,
        requires_screenshot=False, can_indirectly_execute_code=False,
        code_execution_mitigations=None, platforms=ALL_PLATFORMS,
        domain="file", batchable=False, idempotent=True,
    ),
    ToolMetadata(
        name="create_folder",
        description="Create a new directory",
        risk_level=RiskLevel.LOW, reversible=True, reversible_notes=None,
        requires_confirmation=False,
        conditional_confirmation_rules=["Block if directory already exists"],
        data_egress=False, egress_type="none", network_behavior=None,
        path_scope_required=True, max_files_without_confirmation=None,
        max_total_bytes_without_confirmation=None, overwrite_policy="block",
        secret_scan_required=False, requires_diff_preview=False,
        dry_run_supported=True, undo_supported=True, atomic=True,
        requires_screenshot=False, can_indirectly_execute_code=False,
        code_execution_mitigations=None, platforms=ALL_PLATFORMS,
        domain="file", batchable=True, idempotent=False,
    ),
    ToolMetadata(
        name="create_file",
        description="Create a new file or overwrite an existing one",
        risk_level=RiskLevel.MEDIUM, reversible=True,
        reversible_notes="Partial — new file reversible; overwrite may not be",
        requires_confirmation=True,
        conditional_confirmation_rules=[
            "If target exists: confirm (show existing size + mtime)",
            "New file: no confirmation required (LOW risk path)",
        ],
        data_egress=False, egress_type="none", network_behavior=None,
        path_scope_required=True, max_files_without_confirmation=None,
        max_total_bytes_without_confirmation=104_857_600,
        overwrite_policy="confirm",
        secret_scan_required=False, requires_diff_preview=True,
        dry_run_supported=True, undo_supported=True, atomic=True,
        requires_screenshot=False, can_indirectly_execute_code=False,
        code_execution_mitigations=None, platforms=ALL_PLATFORMS,
        domain="file", batchable=False, idempotent=False,
    ),
    ToolMetadata(
        name="read_file",
        description="Read and return the contents of a file",
        risk_level=RiskLevel.LOW, reversible=True, reversible_notes=None,
        requires_confirmation=False,
        conditional_confirmation_rules=[
            "Cloud mode + file text > 0 bytes: show data-egress notice"
        ],
        data_egress=True, egress_type="cloud_content", network_behavior="File excerpt sent to LLM",
        path_scope_required=True, max_files_without_confirmation=1,
        max_total_bytes_without_confirmation=104_857_600, overwrite_policy="allow",
        secret_scan_required=False, requires_diff_preview=False,
        dry_run_supported=True, undo_supported=False, atomic=True,
        requires_screenshot=False, can_indirectly_execute_code=False,
        code_execution_mitigations=None, platforms=ALL_PLATFORMS,
        domain="file", batchable=False, idempotent=True,
    ),
    ToolMetadata(
        name="move_file",
        description="Move or rename files",
        risk_level=RiskLevel.MEDIUM, reversible=True,
        reversible_notes="Reversible if destination is accessible",
        requires_confirmation=False,
        conditional_confirmation_rules=[
            "count > 100 OR total_bytes > 500MB OR destination exists: confirm"
        ],
        data_egress=False, egress_type="none", network_behavior=None,
        path_scope_required=True, max_files_without_confirmation=100,
        max_total_bytes_without_confirmation=524_288_000, overwrite_policy="confirm",
        secret_scan_required=False, requires_diff_preview=False,
        dry_run_supported=True, undo_supported=True, atomic=False,
        requires_screenshot=False, can_indirectly_execute_code=False,
        code_execution_mitigations=None, platforms=ALL_PLATFORMS,
        domain="file", batchable=True, idempotent=False,
    ),
    ToolMetadata(
        name="copy_file",
        description="Copy files to a new location",
        risk_level=RiskLevel.LOW, reversible=True, reversible_notes=None,
        requires_confirmation=False,
        conditional_confirmation_rules=["Destination exists: confirm"],
        data_egress=False, egress_type="none", network_behavior=None,
        path_scope_required=True, max_files_without_confirmation=100,
        max_total_bytes_without_confirmation=524_288_000, overwrite_policy="confirm",
        secret_scan_required=False, requires_diff_preview=False,
        dry_run_supported=True, undo_supported=True, atomic=True,
        requires_screenshot=False, can_indirectly_execute_code=False,
        code_execution_mitigations=None, platforms=ALL_PLATFORMS,
        domain="file", batchable=True, idempotent=False,
    ),
    ToolMetadata(
        name="search_files",
        description="Search for files by name pattern or content",
        risk_level=RiskLevel.LOW, reversible=True, reversible_notes=None,
        requires_confirmation=False, conditional_confirmation_rules=[],
        data_egress=False, egress_type="none", network_behavior=None,
        path_scope_required=True, max_files_without_confirmation=None,
        max_total_bytes_without_confirmation=None, overwrite_policy="allow",
        secret_scan_required=False, requires_diff_preview=False,
        dry_run_supported=True, undo_supported=False, atomic=True,
        requires_screenshot=False, can_indirectly_execute_code=False,
        code_execution_mitigations=None, platforms=ALL_PLATFORMS,
        domain="file", batchable=False, idempotent=True,
    ),
    ToolMetadata(
        name="zip_files",
        description="Create a ZIP archive from files or directories",
        risk_level=RiskLevel.LOW, reversible=True, reversible_notes="Delete the created archive to undo",
        requires_confirmation=False,
        conditional_confirmation_rules=["Block if output file already exists"],
        data_egress=False, egress_type="none", network_behavior=None,
        path_scope_required=True, max_files_without_confirmation=10_000,
        max_total_bytes_without_confirmation=2_147_483_648, overwrite_policy="block",
        secret_scan_required=False, requires_diff_preview=False,
        dry_run_supported=True, undo_supported=True, atomic=False,
        requires_screenshot=False, can_indirectly_execute_code=False,
        code_execution_mitigations=None, platforms=ALL_PLATFORMS,
        domain="file", batchable=False, idempotent=False,
    ),
    ToolMetadata(
        name="unzip_archive",
        description="Extract a ZIP archive safely",
        risk_level=RiskLevel.MEDIUM, reversible=True, reversible_notes=None,
        requires_confirmation=False,
        conditional_confirmation_rules=[
            "Executable entries found: confirm",
            "Overwrite existing files: confirm",
        ],
        data_egress=False, egress_type="none", network_behavior=None,
        path_scope_required=True, max_files_without_confirmation=1000,
        max_total_bytes_without_confirmation=524_288_000, overwrite_policy="confirm",
        secret_scan_required=False, requires_diff_preview=False,
        dry_run_supported=True, undo_supported=False, atomic=False,
        requires_screenshot=False, can_indirectly_execute_code=False,
        code_execution_mitigations=["ArchiveSafetyValidator", "ZipSlip prevention"],
        platforms=ALL_PLATFORMS, domain="file", batchable=False, idempotent=False,
    ),
    ToolMetadata(
        name="move_to_trash",
        description="Move files to the system trash/recycle bin",
        risk_level=RiskLevel.HIGH, reversible=True,
        reversible_notes="Only if trash is available; headless Linux: HALT",
        requires_confirmation=True,
        conditional_confirmation_rules=[
            "Always: batch confirmation showing count + total size",
            "Headless Linux without trash: HALT (do not permanently delete)",
        ],
        data_egress=False, egress_type="none", network_behavior=None,
        path_scope_required=True, max_files_without_confirmation=None,
        max_total_bytes_without_confirmation=None, overwrite_policy="allow",
        secret_scan_required=False, requires_diff_preview=False,
        dry_run_supported=True, undo_supported=False, atomic=False,
        requires_screenshot=False, can_indirectly_execute_code=False,
        code_execution_mitigations=None, platforms=ALL_PLATFORMS,
        domain="file", batchable=True, idempotent=False,
    ),
    ToolMetadata(
        name="open_known_app",
        description="Open a known application by display name",
        risk_level=RiskLevel.MEDIUM, reversible=True, reversible_notes=None,
        requires_confirmation=False,
        conditional_confirmation_rules=[
            "Resolved app path outside known app directories: BLOCK (not confirm)"
        ],
        data_egress=False, egress_type="none", network_behavior=None,
        path_scope_required=False, max_files_without_confirmation=None,
        max_total_bytes_without_confirmation=None, overwrite_policy="allow",
        secret_scan_required=False, requires_diff_preview=False,
        dry_run_supported=True, undo_supported=True, atomic=True,
        requires_screenshot=True, can_indirectly_execute_code=True,
        code_execution_mitigations=["Name-to-known-directory lookup only; no arbitrary paths"],
        platforms=ALL_PLATFORMS, domain="app", batchable=False, idempotent=False,
    ),
    ToolMetadata(
        name="close_app",
        description="Close a running application",
        risk_level=RiskLevel.MEDIUM, reversible=False, reversible_notes=None,
        requires_confirmation=False, conditional_confirmation_rules=[],
        data_egress=False, egress_type="none", network_behavior=None,
        path_scope_required=False, max_files_without_confirmation=None,
        max_total_bytes_without_confirmation=None, overwrite_policy="allow",
        secret_scan_required=False, requires_diff_preview=False,
        dry_run_supported=True, undo_supported=False, atomic=True,
        requires_screenshot=True, can_indirectly_execute_code=False,
        code_execution_mitigations=None, platforms=ALL_PLATFORMS,
        domain="app", batchable=False, idempotent=False,
    ),
    ToolMetadata(
        name="list_running_apps",
        description="List currently running applications",
        risk_level=RiskLevel.LOW, reversible=True, reversible_notes=None,
        requires_confirmation=False, conditional_confirmation_rules=[],
        data_egress=False, egress_type="none", network_behavior=None,
        path_scope_required=False, max_files_without_confirmation=None,
        max_total_bytes_without_confirmation=None, overwrite_policy="allow",
        secret_scan_required=False, requires_diff_preview=False,
        dry_run_supported=True, undo_supported=False, atomic=True,
        requires_screenshot=False, can_indirectly_execute_code=False,
        code_execution_mitigations=None, platforms=ALL_PLATFORMS,
        domain="app", batchable=False, idempotent=True,
    ),
    ToolMetadata(
        name="system_monitor",
        description="Read system metrics: CPU, RAM, disk, uptime, processes",
        risk_level=RiskLevel.LOW, reversible=True, reversible_notes=None,
        requires_confirmation=False,
        conditional_confirmation_rules=[
            "Cloud mode + LLM analysis requested: show data-egress notice"
        ],
        data_egress=True, egress_type="cloud_metadata",
        network_behavior="System metadata optionally sent to LLM",
        path_scope_required=False, max_files_without_confirmation=None,
        max_total_bytes_without_confirmation=None, overwrite_policy="allow",
        secret_scan_required=False, requires_diff_preview=False,
        dry_run_supported=True, undo_supported=False, atomic=True,
        requires_screenshot=False, can_indirectly_execute_code=False,
        code_execution_mitigations=None, platforms=ALL_PLATFORMS,
        domain="system", batchable=False, idempotent=True,
    ),
    ToolMetadata(
        name="browser_open_url",
        description="Open a URL in the isolated browser",
        risk_level=RiskLevel.MEDIUM, reversible=True, reversible_notes=None,
        requires_confirmation=False,
        conditional_confirmation_rules=["URL checked against blocklist before dispatch"],
        data_egress=True, egress_type="browser",
        network_behavior="HTTP request to target URL; screenshot sent to LLM",
        path_scope_required=False, max_files_without_confirmation=None,
        max_total_bytes_without_confirmation=None, overwrite_policy="allow",
        secret_scan_required=False, requires_diff_preview=False,
        dry_run_supported=True, undo_supported=True, atomic=True,
        requires_screenshot=True, can_indirectly_execute_code=False,
        code_execution_mitigations=["Isolated browser profile; URL blocklist"],
        platforms=ALL_PLATFORMS, domain="browser", batchable=False, idempotent=False,
    ),
    ToolMetadata(
        name="browser_web_search",
        description="Perform a web search in the isolated browser",
        risk_level=RiskLevel.MEDIUM, reversible=True, reversible_notes=None,
        requires_confirmation=False, conditional_confirmation_rules=[],
        data_egress=True, egress_type="browser",
        network_behavior="Search query sent to search engine; results sent to LLM",
        path_scope_required=False, max_files_without_confirmation=None,
        max_total_bytes_without_confirmation=None, overwrite_policy="allow",
        secret_scan_required=False, requires_diff_preview=False,
        dry_run_supported=True, undo_supported=True, atomic=True,
        requires_screenshot=True, can_indirectly_execute_code=False,
        code_execution_mitigations=["Isolated browser profile"],
        platforms=ALL_PLATFORMS, domain="browser", batchable=False, idempotent=False,
    ),
    ToolMetadata(
        name="browser_extract_page_text",
        description="Extract text content from the current browser page",
        risk_level=RiskLevel.MEDIUM, reversible=True, reversible_notes=None,
        requires_confirmation=False,
        conditional_confirmation_rules=[
            "Cloud mode + page text > 0 bytes: show data-egress notice"
        ],
        data_egress=True, egress_type="cloud_content",
        network_behavior="Page text excerpt sent to Sanitizer LLM",
        path_scope_required=False, max_files_without_confirmation=None,
        max_total_bytes_without_confirmation=None, overwrite_policy="allow",
        secret_scan_required=False, requires_diff_preview=False,
        dry_run_supported=True, undo_supported=False, atomic=True,
        requires_screenshot=True, can_indirectly_execute_code=False,
        code_execution_mitigations=["Sanitizer LLM; IPI detection"],
        platforms=ALL_PLATFORMS, domain="browser", batchable=False, idempotent=True,
    ),
    ToolMetadata(
        name="browser_download_file",
        description="Download a file from the browser to ~/.pacca/downloads/",
        risk_level=RiskLevel.MEDIUM, reversible=True, reversible_notes=None,
        requires_confirmation=False,
        conditional_confirmation_rules=[
            "Executable/script/archive extension: require YES; show MIME + extension"
        ],
        data_egress=True, egress_type="browser",
        network_behavior="File downloaded from URL; no auto-open",
        path_scope_required=False, max_files_without_confirmation=None,
        max_total_bytes_without_confirmation=209_715_200, overwrite_policy="confirm",
        secret_scan_required=False, requires_diff_preview=False,
        dry_run_supported=True, undo_supported=True, atomic=True,
        requires_screenshot=False, can_indirectly_execute_code=False,
        code_execution_mitigations=["MIME check; no auto-open; quarantine applied"],
        platforms=ALL_PLATFORMS, domain="browser", batchable=False, idempotent=False,
    ),
    ToolMetadata(
        name="browser_tab_management",
        description="Open, close, or switch browser tabs",
        risk_level=RiskLevel.LOW, reversible=True, reversible_notes=None,
        requires_confirmation=False, conditional_confirmation_rules=[],
        data_egress=False, egress_type="none",
        network_behavior="Tab navigation only",
        path_scope_required=False, max_files_without_confirmation=None,
        max_total_bytes_without_confirmation=None, overwrite_policy="allow",
        secret_scan_required=False, requires_diff_preview=False,
        dry_run_supported=True, undo_supported=True, atomic=True,
        requires_screenshot=False, can_indirectly_execute_code=False,
        code_execution_mitigations=None, platforms=ALL_PLATFORMS,
        domain="browser", batchable=False, idempotent=False,
    ),
    ToolMetadata(
        name="create_docx",
        description="Create a new Word document (.docx)",
        risk_level=RiskLevel.LOW, reversible=True, reversible_notes=None,
        requires_confirmation=False,
        conditional_confirmation_rules=["Block if file already exists"],
        data_egress=False, egress_type="none", network_behavior=None,
        path_scope_required=True, max_files_without_confirmation=None,
        max_total_bytes_without_confirmation=52_428_800, overwrite_policy="block",
        secret_scan_required=False, requires_diff_preview=False,
        dry_run_supported=True, undo_supported=True, atomic=True,
        requires_screenshot=False, can_indirectly_execute_code=False,
        code_execution_mitigations=None, platforms=ALL_PLATFORMS,
        domain="document", batchable=False, idempotent=False,
    ),
    ToolMetadata(
        name="read_docx",
        description="Read text content from a Word document",
        risk_level=RiskLevel.LOW, reversible=True, reversible_notes=None,
        requires_confirmation=False,
        conditional_confirmation_rules=[
            "Cloud mode + content > 0 bytes: show data-egress notice"
        ],
        data_egress=True, egress_type="cloud_content",
        network_behavior="Document text excerpt sent to LLM",
        path_scope_required=True, max_files_without_confirmation=1,
        max_total_bytes_without_confirmation=52_428_800, overwrite_policy="allow",
        secret_scan_required=False, requires_diff_preview=False,
        dry_run_supported=True, undo_supported=False, atomic=True,
        requires_screenshot=False, can_indirectly_execute_code=False,
        code_execution_mitigations=None, platforms=ALL_PLATFORMS,
        domain="document", batchable=False, idempotent=True,
    ),
    ToolMetadata(
        name="create_xlsx",
        description="Create a new Excel spreadsheet (.xlsx)",
        risk_level=RiskLevel.LOW, reversible=True, reversible_notes=None,
        requires_confirmation=False,
        conditional_confirmation_rules=["Block if file already exists"],
        data_egress=False, egress_type="none", network_behavior=None,
        path_scope_required=True, max_files_without_confirmation=None,
        max_total_bytes_without_confirmation=52_428_800, overwrite_policy="block",
        secret_scan_required=False, requires_diff_preview=False,
        dry_run_supported=True, undo_supported=True, atomic=True,
        requires_screenshot=False, can_indirectly_execute_code=False,
        code_execution_mitigations=None, platforms=ALL_PLATFORMS,
        domain="document", batchable=False, idempotent=False,
    ),
    ToolMetadata(
        name="read_xlsx",
        description="Read data from an Excel spreadsheet",
        risk_level=RiskLevel.LOW, reversible=True, reversible_notes=None,
        requires_confirmation=False,
        conditional_confirmation_rules=[
            "Cloud mode + content > 0 bytes: show data-egress notice"
        ],
        data_egress=True, egress_type="cloud_content",
        network_behavior="Spreadsheet excerpt sent to LLM",
        path_scope_required=True, max_files_without_confirmation=1,
        max_total_bytes_without_confirmation=52_428_800, overwrite_policy="allow",
        secret_scan_required=False, requires_diff_preview=False,
        dry_run_supported=True, undo_supported=False, atomic=True,
        requires_screenshot=False, can_indirectly_execute_code=False,
        code_execution_mitigations=None, platforms=ALL_PLATFORMS,
        domain="document", batchable=False, idempotent=True,
    ),
    ToolMetadata(
        name="git_status",
        description="Show the working tree status of a git repository",
        risk_level=RiskLevel.LOW, reversible=True, reversible_notes=None,
        requires_confirmation=False, conditional_confirmation_rules=[],
        data_egress=False, egress_type="none", network_behavior=None,
        path_scope_required=True, max_files_without_confirmation=None,
        max_total_bytes_without_confirmation=None, overwrite_policy="allow",
        secret_scan_required=False, requires_diff_preview=False,
        dry_run_supported=True, undo_supported=False, atomic=True,
        requires_screenshot=False, can_indirectly_execute_code=False,
        code_execution_mitigations=None, platforms=ALL_PLATFORMS,
        domain="git", batchable=False, idempotent=True,
    ),
    ToolMetadata(
        name="git_diff",
        description="Show git diff of working tree or staged changes",
        risk_level=RiskLevel.LOW, reversible=True, reversible_notes=None,
        requires_confirmation=False,
        conditional_confirmation_rules=[
            "Cloud mode + diff sent to LLM: show data-egress notice"
        ],
        data_egress=True, egress_type="cloud_content",
        network_behavior="Diff excerpt optionally sent to LLM",
        path_scope_required=True, max_files_without_confirmation=None,
        max_total_bytes_without_confirmation=None, overwrite_policy="allow",
        secret_scan_required=True, requires_diff_preview=False,
        dry_run_supported=True, undo_supported=False, atomic=True,
        requires_screenshot=False, can_indirectly_execute_code=False,
        code_execution_mitigations=None, platforms=ALL_PLATFORMS,
        domain="git", batchable=False, idempotent=True,
    ),
    ToolMetadata(
        name="git_add",
        description="Stage files for commit",
        risk_level=RiskLevel.LOW, reversible=True, reversible_notes=None,
        requires_confirmation=False,
        conditional_confirmation_rules=[
            "Staged file matches SECRET_PATTERNS: HALT; show file + pattern; no override"
        ],
        data_egress=False, egress_type="none", network_behavior=None,
        path_scope_required=True, max_files_without_confirmation=500,
        max_total_bytes_without_confirmation=None, overwrite_policy="allow",
        secret_scan_required=True, requires_diff_preview=False,
        dry_run_supported=True, undo_supported=True, atomic=True,
        requires_screenshot=False, can_indirectly_execute_code=True,
        code_execution_mitigations=["LFS filter warning; submodule warning"],
        platforms=ALL_PLATFORMS, domain="git", batchable=True, idempotent=False,
    ),
    ToolMetadata(
        name="git_commit",
        description="Commit staged changes to a git repository",
        risk_level=RiskLevel.MEDIUM, reversible=False,
        reversible_notes="Irreversible locally (can be undone with git reset in v1.1)",
        requires_confirmation=True,
        conditional_confirmation_rules=[
            "Always: secret scan staged diff; diff preview; require YES",
            "--no-verify is mandatory and non-configurable",
        ],
        data_egress=False, egress_type="none", network_behavior=None,
        path_scope_required=True, max_files_without_confirmation=None,
        max_total_bytes_without_confirmation=None, overwrite_policy="allow",
        secret_scan_required=True, requires_diff_preview=True,
        dry_run_supported=True, undo_supported=False, atomic=True,
        requires_screenshot=False, can_indirectly_execute_code=True,
        code_execution_mitigations=["--no-verify mandatory; hook detection informational"],
        platforms=ALL_PLATFORMS, domain="git", batchable=False, idempotent=False,
    ),
]

TOOL_REGISTRY: dict[str, ToolMetadata] = {t.name: t for t in _REGISTRY_DATA}

_POLICY_VERSION = hashlib.sha256(
    json.dumps(
        {name: meta.risk_level.value for name, meta in TOOL_REGISTRY.items()},
        sort_keys=True
    ).encode()
).hexdigest()[:16]


def get_tool(name: str) -> ToolMetadata | None:
    return TOOL_REGISTRY.get(name)


def list_tools() -> list[str]:
    return sorted(TOOL_REGISTRY.keys())


def policy_version() -> str:
    return _POLICY_VERSION
