"""Tool registry — 38 tools (28 original + 10 new: vision, coding, research)."""
from __future__ import annotations
import hashlib
import json
from arix.models.tool_metadata import ToolMetadata, RiskLevel

ALL_PLATFORMS = ["darwin", "win32", "linux"]

_REGISTRY_DATA = [
    ToolMetadata(
        name="list_directory",
        description="List contents of a directory",
        risk_level=RiskLevel.LOW, reversible=True, reversible_notes=None,
        requires_confirmation=False, conditional_confirmation_rules=[],
        data_egress=False, egress_type="none", network_behavior=None,
        path_scope_required=True, max_files_without_confirmation=None,
        max_total_bytes_without_confirmation=None, overwrite_policy="allow",
        secret_scan_required=False, requires_diff_preview=False,
        dry_run_supported=True, undo_supported=False, atomic=True,
        requires_screenshot=False, can_indirectly_execute_code=False,
        code_execution_mitigations=None, platforms=ALL_PLATFORMS,
        domain="file", batchable=False, idempotent=True,
    ),
    ToolMetadata(
        name="create_folder",
        description="Create a new directory",
        risk_level=RiskLevel.LOW, reversible=True, reversible_notes=None,
        requires_confirmation=False,
        conditional_confirmation_rules=["Block if directory already exists"],
        data_egress=False, egress_type="none", network_behavior=None,
        path_scope_required=True, max_files_without_confirmation=None,
        max_total_bytes_without_confirmation=None, overwrite_policy="block",
        secret_scan_required=False, requires_diff_preview=False,
        dry_run_supported=True, undo_supported=True, atomic=True,
        requires_screenshot=False, can_indirectly_execute_code=False,
        code_execution_mitigations=None, platforms=ALL_PLATFORMS,
        domain="file", batchable=True, idempotent=False,
    ),
    ToolMetadata(
        name="create_file",
        description="Create a new file or overwrite an existing one",
        risk_level=RiskLevel.MEDIUM, reversible=True,
        reversible_notes="Partial — new file reversible; overwrite may not be",
        requires_confirmation=True,
        conditional_confirmation_rules=[
            "If target exists: confirm (show existing size + mtime)",
            "New file: no confirmation required (LOW risk path)",
        ],
        data_egress=False, egress_type="none", network_behavior=None,
        path_scope_required=True, max_files_without_confirmation=None,
        max_total_bytes_without_confirmation=104_857_600,
        overwrite_policy="confirm",
        secret_scan_required=False, requires_diff_preview=True,
        dry_run_supported=True, undo_supported=True, atomic=True,
        requires_screenshot=False, can_indirectly_execute_code=False,
        code_execution_mitigations=None, platforms=ALL_PLATFORMS,
        domain="file", batchable=False, idempotent=False,
    ),
    ToolMetadata(
        name="read_file",
        description="Read and return the contents of a file",
        risk_level=RiskLevel.LOW, reversible=True, reversible_notes=None,
        requires_confirmation=False,
        conditional_confirmation_rules=[
            "Cloud mode + file text > 0 bytes: show data-egress notice"
        ],
        data_egress=True, egress_type="cloud_content", network_behavior="File excerpt sent to LLM",
        path_scope_required=True, max_files_without_confirmation=1,
        max_total_bytes_without_confirmation=104_857_600, overwrite_policy="allow",
        secret_scan_required=False, requires_diff_preview=False,
        dry_run_supported=True, undo_supported=False, atomic=True,
        requires_screenshot=False, can_indirectly_execute_code=False,
        code_execution_mitigations=None, platforms=ALL_PLATFORMS,
        domain="file", batchable=False, idempotent=True,
    ),
    ToolMetadata(
        name="move_file",
        description="Move or rename files",
        risk_level=RiskLevel.MEDIUM, reversible=True,
        reversible_notes="Reversible if destination is accessible",
        requires_confirmation=False,
        conditional_confirmation_rules=[
            "count > 100 OR total_bytes > 500MB OR destination exists: confirm"
        ],
        data_egress=False, egress_type="none", network_behavior=None,
        path_scope_required=True, max_files_without_confirmation=100,
        max_total_bytes_without_confirmation=524_288_000, overwrite_policy="confirm",
        secret_scan_required=False, requires_diff_preview=False,
        dry_run_supported=True, undo_supported=True, atomic=False,
        requires_screenshot=False, can_indirectly_execute_code=False,
        code_execution_mitigations=None, platforms=ALL_PLATFORMS,
        domain="file", batchable=True, idempotent=False,
    ),
    ToolMetadata(
        name="copy_file",
        description="Copy files to a new location",
        risk_level=RiskLevel.LOW, reversible=True, reversible_notes=None,
        requires_confirmation=False,
        conditional_confirmation_rules=["Destination exists: confirm"],
        data_egress=False, egress_type="none", network_behavior=None,
        path_scope_required=True, max_files_without_confirmation=100,
        max_total_bytes_without_confirmation=524_288_000, overwrite_policy="confirm",
        secret_scan_required=False, requires_diff_preview=False,
        dry_run_supported=True, undo_supported=True, atomic=True,
        requires_screenshot=False, can_indirectly_execute_code=False,
        code_execution_mitigations=None, platforms=ALL_PLATFORMS,
        domain="file", batchable=True, idempotent=False,
    ),
    ToolMetadata(
        name="search_files",
        description="Search for files by name pattern or content",
        risk_level=RiskLevel.LOW, reversible=True, reversible_notes=None,
        requires_confirmation=False, conditional_confirmation_rules=[],
        data_egress=False, egress_type="none", network_behavior=None,
        path_scope_required=True, max_files_without_confirmation=None,
        max_total_bytes_without_confirmation=None, overwrite_policy="allow",
        secret_scan_required=False, requires_diff_preview=False,
        dry_run_supported=True, undo_supported=False, atomic=True,
        requires_screenshot=False, can_indirectly_execute_code=False,
        code_execution_mitigations=None, platforms=ALL_PLATFORMS,
        domain="file", batchable=False, idempotent=True,
    ),
    ToolMetadata(
        name="zip_files",
        description="Create a ZIP archive from files or directories",
        risk_level=RiskLevel.LOW, reversible=True, reversible_notes="Delete the created archive to undo",
        requires_confirmation=False,
        conditional_confirmation_rules=["Block if output file already exists"],
        data_egress=False, egress_type="none", network_behavior=None,
        path_scope_required=True, max_files_without_confirmation=10_000,
        max_total_bytes_without_confirmation=2_147_483_648, overwrite_policy="block",
        secret_scan_required=False, requires_diff_preview=False,
        dry_run_supported=True, undo_supported=True, atomic=False,
        requires_screenshot=False, can_indirectly_execute_code=False,
        code_execution_mitigations=None, platforms=ALL_PLATFORMS,
        domain="file", batchable=False, idempotent=False,
    ),
    ToolMetadata(
        name="unzip_archive",
        description="Extract a ZIP archive safely",
        risk_level=RiskLevel.MEDIUM, reversible=True, reversible_notes=None,
        requires_confirmation=False,
        conditional_confirmation_rules=[
            "Executable entries found: confirm",
            "Overwrite existing files: confirm",
        ],
        data_egress=False, egress_type="none", network_behavior=None,
        path_scope_required=True, max_files_without_confirmation=1000,
        max_total_bytes_without_confirmation=524_288_000, overwrite_policy="confirm",
        secret_scan_required=False, requires_diff_preview=False,
        dry_run_supported=True, undo_supported=False, atomic=False,
        requires_screenshot=False, can_indirectly_execute_code=False,
        code_execution_mitigations=["ArchiveSafetyValidator", "ZipSlip prevention"],
        platforms=ALL_PLATFORMS, domain="file", batchable=False, idempotent=False,
    ),
    ToolMetadata(
        name="move_to_trash",
        description="Move files to the system trash/recycle bin",
        risk_level=RiskLevel.HIGH, reversible=True,
        reversible_notes="Only if trash is available; headless Linux: HALT",
        requires_confirmation=True,
        conditional_confirmation_rules=[
            "Always: batch confirmation showing count + total size",
            "Headless Linux without trash: HALT (do not permanently delete)",
        ],
        data_egress=False, egress_type="none", network_behavior=None,
        path_scope_required=True, max_files_without_confirmation=None,
        max_total_bytes_without_confirmation=None, overwrite_policy="allow",
        secret_scan_required=False, requires_diff_preview=False,
        dry_run_supported=True, undo_supported=False, atomic=False,
        requires_screenshot=False, can_indirectly_execute_code=False,
        code_execution_mitigations=None, platforms=ALL_PLATFORMS,
        domain="file", batchable=True, idempotent=False,
    ),
    ToolMetadata(
        name="open_known_app",
        description="Open a known application by display name",
        risk_level=RiskLevel.MEDIUM, reversible=True, reversible_notes=None,
        requires_confirmation=False,
        conditional_confirmation_rules=[
            "Resolved app path outside known app directories: BLOCK (not confirm)"
        ],
        data_egress=False, egress_type="none", network_behavior=None,
        path_scope_required=False, max_files_without_confirmation=None,
        max_total_bytes_without_confirmation=None, overwrite_policy="allow",
        secret_scan_required=False, requires_diff_preview=False,
        dry_run_supported=True, undo_supported=True, atomic=True,
        requires_screenshot=True, can_indirectly_execute_code=True,
        code_execution_mitigations=["Name-to-known-directory lookup only; no arbitrary paths"],
        platforms=ALL_PLATFORMS, domain="app", batchable=False, idempotent=False,
    ),
    ToolMetadata(
        name="close_app",
        description="Close a running application",
        risk_level=RiskLevel.MEDIUM, reversible=False, reversible_notes=None,
        requires_confirmation=False, conditional_confirmation_rules=[],
        data_egress=False, egress_type="none", network_behavior=None,
        path_scope_required=False, max_files_without_confirmation=None,
        max_total_bytes_without_confirmation=None, overwrite_policy="allow",
        secret_scan_required=False, requires_diff_preview=False,
        dry_run_supported=True, undo_supported=False, atomic=True,
        requires_screenshot=True, can_indirectly_execute_code=False,
        code_execution_mitigations=None, platforms=ALL_PLATFORMS,
        domain="app", batchable=False, idempotent=False,
    ),
    ToolMetadata(
        name="list_running_apps",
        description="List currently running applications",
        risk_level=RiskLevel.LOW, reversible=True, reversible_notes=None,
        requires_confirmation=False, conditional_confirmation_rules=[],
        data_egress=False, egress_type="none", network_behavior=None,
        path_scope_required=False, max_files_without_confirmation=None,
        max_total_bytes_without_confirmation=None, overwrite_policy="allow",
        secret_scan_required=False, requires_diff_preview=False,
        dry_run_supported=True, undo_supported=False, atomic=True,
        requires_screenshot=False, can_indirectly_execute_code=False,
        code_execution_mitigations=None, platforms=ALL_PLATFORMS,
        domain="app", batchable=False, idempotent=True,
    ),
    ToolMetadata(
        name="system_monitor",
        description="Read system metrics: CPU, RAM, disk, uptime, processes",
        risk_level=RiskLevel.LOW, reversible=True, reversible_notes=None,
        requires_confirmation=False,
        conditional_confirmation_rules=[
            "Cloud mode + LLM analysis requested: show data-egress notice"
        ],
        data_egress=True, egress_type="cloud_metadata",
        network_behavior="System metadata optionally sent to LLM",
        path_scope_required=False, max_files_without_confirmation=None,
        max_total_bytes_without_confirmation=None, overwrite_policy="allow",
        secret_scan_required=False, requires_diff_preview=False,
        dry_run_supported=True, undo_supported=False, atomic=True,
        requires_screenshot=False, can_indirectly_execute_code=False,
        code_execution_mitigations=None, platforms=ALL_PLATFORMS,
        domain="system", batchable=False, idempotent=True,
    ),
    ToolMetadata(
        name="browser_open_url",
        description="Open a URL in the isolated browser",
        risk_level=RiskLevel.MEDIUM, reversible=True, reversible_notes=None,
        requires_confirmation=False,
        conditional_confirmation_rules=["URL checked against blocklist before dispatch"],
        data_egress=True, egress_type="browser",
        network_behavior="HTTP request to target URL; screenshot sent to LLM",
        path_scope_required=False, max_files_without_confirmation=None,
        max_total_bytes_without_confirmation=None, overwrite_policy="allow",
        secret_scan_required=False, requires_diff_preview=False,
        dry_run_supported=True, undo_supported=True, atomic=True,
        requires_screenshot=True, can_indirectly_execute_code=False,
        code_execution_mitigations=["Isolated browser profile; URL blocklist"],
        platforms=ALL_PLATFORMS, domain="browser", batchable=False, idempotent=False,
    ),
    ToolMetadata(
        name="browser_web_search",
        description="Perform a web search in the isolated browser",
        risk_level=RiskLevel.MEDIUM, reversible=True, reversible_notes=None,
        requires_confirmation=False, conditional_confirmation_rules=[],
        data_egress=True, egress_type="browser",
        network_behavior="Search query sent to search engine; results sent to LLM",
        path_scope_required=False, max_files_without_confirmation=None,
        max_total_bytes_without_confirmation=None, overwrite_policy="allow",
        secret_scan_required=False, requires_diff_preview=False,
        dry_run_supported=True, undo_supported=True, atomic=True,
        requires_screenshot=True, can_indirectly_execute_code=False,
        code_execution_mitigations=["Isolated browser profile"],
        platforms=ALL_PLATFORMS, domain="browser", batchable=False, idempotent=False,
    ),
    ToolMetadata(
        name="browser_extract_page_text",
        description="Extract text content from the current browser page",
        risk_level=RiskLevel.MEDIUM, reversible=True, reversible_notes=None,
        requires_confirmation=False,
        conditional_confirmation_rules=[
            "Cloud mode + page text > 0 bytes: show data-egress notice"
        ],
        data_egress=True, egress_type="cloud_content",
        network_behavior="Page text excerpt sent to Sanitizer LLM",
        path_scope_required=False, max_files_without_confirmation=None,
        max_total_bytes_without_confirmation=None, overwrite_policy="allow",
        secret_scan_required=False, requires_diff_preview=False,
        dry_run_supported=True, undo_supported=False, atomic=True,
        requires_screenshot=True, can_indirectly_execute_code=False,
        code_execution_mitigations=["Sanitizer LLM; IPI detection"],
        platforms=ALL_PLATFORMS, domain="browser", batchable=False, idempotent=True,
    ),
    ToolMetadata(
        name="browser_download_file",
        description="Download a file from the browser to ~/.arix/downloads/",
        risk_level=RiskLevel.MEDIUM, reversible=True, reversible_notes=None,
        requires_confirmation=False,
        conditional_confirmation_rules=[
            "Executable/script/archive extension: require YES; show MIME + extension"
        ],
        data_egress=True, egress_type="browser",
        network_behavior="File downloaded from URL; no auto-open",
        path_scope_required=False, max_files_without_confirmation=None,
        max_total_bytes_without_confirmation=209_715_200, overwrite_policy="confirm",
        secret_scan_required=False, requires_diff_preview=False,
        dry_run_supported=True, undo_supported=True, atomic=True,
        requires_screenshot=False, can_indirectly_execute_code=False,
        code_execution_mitigations=["MIME check; no auto-open; quarantine applied"],
        platforms=ALL_PLATFORMS, domain="browser", batchable=False, idempotent=False,
    ),
    ToolMetadata(
        name="browser_tab_management",
        description="Open, close, or switch browser tabs",
        risk_level=RiskLevel.LOW, reversible=True, reversible_notes=None,
        requires_confirmation=False, conditional_confirmation_rules=[],
        data_egress=False, egress_type="none",
        network_behavior="Tab navigation only",
        path_scope_required=False, max_files_without_confirmation=None,
        max_total_bytes_without_confirmation=None, overwrite_policy="allow",
        secret_scan_required=False, requires_diff_preview=False,
        dry_run_supported=True, undo_supported=True, atomic=True,
        requires_screenshot=False, can_indirectly_execute_code=False,
        code_execution_mitigations=None, platforms=ALL_PLATFORMS,
        domain="browser", batchable=False, idempotent=False,
    ),
    ToolMetadata(
        name="create_docx",
        description="Create a new Word document (.docx)",
        risk_level=RiskLevel.LOW, reversible=True, reversible_notes=None,
        requires_confirmation=False,
        conditional_confirmation_rules=["Block if file already exists"],
        data_egress=False, egress_type="none", network_behavior=None,
        path_scope_required=True, max_files_without_confirmation=None,
        max_total_bytes_without_confirmation=52_428_800, overwrite_policy="block",
        secret_scan_required=False, requires_diff_preview=False,
        dry_run_supported=True, undo_supported=True, atomic=True,
        requires_screenshot=False, can_indirectly_execute_code=False,
        code_execution_mitigations=None, platforms=ALL_PLATFORMS,
        domain="document", batchable=False, idempotent=False,
    ),
    ToolMetadata(
        name="read_docx",
        description="Read text content from a Word document",
        risk_level=RiskLevel.LOW, reversible=True, reversible_notes=None,
        requires_confirmation=False,
        conditional_confirmation_rules=[
            "Cloud mode + content > 0 bytes: show data-egress notice"
        ],
        data_egress=True, egress_type="cloud_content",
        network_behavior="Document text excerpt sent to LLM",
        path_scope_required=True, max_files_without_confirmation=1,
        max_total_bytes_without_confirmation=52_428_800, overwrite_policy="allow",
        secret_scan_required=False, requires_diff_preview=False,
        dry_run_supported=True, undo_supported=False, atomic=True,
        requires_screenshot=False, can_indirectly_execute_code=False,
        code_execution_mitigations=None, platforms=ALL_PLATFORMS,
        domain="document", batchable=False, idempotent=True,
    ),
    ToolMetadata(
        name="create_xlsx",
        description="Create a new Excel spreadsheet (.xlsx)",
        risk_level=RiskLevel.LOW, reversible=True, reversible_notes=None,
        requires_confirmation=False,
        conditional_confirmation_rules=["Block if file already exists"],
        data_egress=False, egress_type="none", network_behavior=None,
        path_scope_required=True, max_files_without_confirmation=None,
        max_total_bytes_without_confirmation=52_428_800, overwrite_policy="block",
        secret_scan_required=False, requires_diff_preview=False,
        dry_run_supported=True, undo_supported=True, atomic=True,
        requires_screenshot=False, can_indirectly_execute_code=False,
        code_execution_mitigations=None, platforms=ALL_PLATFORMS,
        domain="document", batchable=False, idempotent=False,
    ),
    ToolMetadata(
        name="read_xlsx",
        description="Read data from an Excel spreadsheet",
        risk_level=RiskLevel.LOW, reversible=True, reversible_notes=None,
        requires_confirmation=False,
        conditional_confirmation_rules=[
            "Cloud mode + content > 0 bytes: show data-egress notice"
        ],
        data_egress=True, egress_type="cloud_content",
        network_behavior="Spreadsheet excerpt sent to LLM",
        path_scope_required=True, max_files_without_confirmation=1,
        max_total_bytes_without_confirmation=52_428_800, overwrite_policy="allow",
        secret_scan_required=False, requires_diff_preview=False,
        dry_run_supported=True, undo_supported=False, atomic=True,
        requires_screenshot=False, can_indirectly_execute_code=False,
        code_execution_mitigations=None, platforms=ALL_PLATFORMS,
        domain="document", batchable=False, idempotent=True,
    ),
    ToolMetadata(
        name="git_status",
        description="Show the working tree status of a git repository",
        risk_level=RiskLevel.LOW, reversible=True, reversible_notes=None,
        requires_confirmation=False, conditional_confirmation_rules=[],
        data_egress=False, egress_type="none", network_behavior=None,
        path_scope_required=True, max_files_without_confirmation=None,
        max_total_bytes_without_confirmation=None, overwrite_policy="allow",
        secret_scan_required=False, requires_diff_preview=False,
        dry_run_supported=True, undo_supported=False, atomic=True,
        requires_screenshot=False, can_indirectly_execute_code=False,
        code_execution_mitigations=None, platforms=ALL_PLATFORMS,
        domain="git", batchable=False, idempotent=True,
    ),
    ToolMetadata(
        name="git_diff",
        description="Show git diff of working tree or staged changes",
        risk_level=RiskLevel.LOW, reversible=True, reversible_notes=None,
        requires_confirmation=False,
        conditional_confirmation_rules=[
            "Cloud mode + diff sent to LLM: show data-egress notice"
        ],
        data_egress=True, egress_type="cloud_content",
        network_behavior="Diff excerpt optionally sent to LLM",
        path_scope_required=True, max_files_without_confirmation=None,
        max_total_bytes_without_confirmation=None, overwrite_policy="allow",
        secret_scan_required=True, requires_diff_preview=False,
        dry_run_supported=True, undo_supported=False, atomic=True,
        requires_screenshot=False, can_indirectly_execute_code=False,
        code_execution_mitigations=None, platforms=ALL_PLATFORMS,
        domain="git", batchable=False, idempotent=True,
    ),
    ToolMetadata(
        name="git_add",
        description="Stage files for commit",
        risk_level=RiskLevel.LOW, reversible=True, reversible_notes=None,
        requires_confirmation=False,
        conditional_confirmation_rules=[
            "Staged file matches SECRET_PATTERNS: HALT; show file + pattern; no override"
        ],
        data_egress=False, egress_type="none", network_behavior=None,
        path_scope_required=True, max_files_without_confirmation=500,
        max_total_bytes_without_confirmation=None, overwrite_policy="allow",
        secret_scan_required=True, requires_diff_preview=False,
        dry_run_supported=True, undo_supported=True, atomic=True,
        requires_screenshot=False, can_indirectly_execute_code=True,
        code_execution_mitigations=["LFS filter warning; submodule warning"],
        platforms=ALL_PLATFORMS, domain="git", batchable=True, idempotent=False,
    ),
    ToolMetadata(
        name="git_commit",
        description="Commit staged changes to a git repository",
        risk_level=RiskLevel.MEDIUM, reversible=False,
        reversible_notes="Irreversible locally (can be undone with git reset in v1.1)",
        requires_confirmation=True,
        conditional_confirmation_rules=[
            "Always: secret scan staged diff; diff preview; require YES",
            "--no-verify is mandatory and non-configurable",
        ],
        data_egress=False, egress_type="none", network_behavior=None,
        path_scope_required=True, max_files_without_confirmation=None,
        max_total_bytes_without_confirmation=None, overwrite_policy="allow",
        secret_scan_required=True, requires_diff_preview=True,
        dry_run_supported=True, undo_supported=False, atomic=True,
        requires_screenshot=False, can_indirectly_execute_code=True,
        code_execution_mitigations=["--no-verify mandatory; hook detection informational"],
        platforms=ALL_PLATFORMS, domain="git", batchable=False, idempotent=False,
    ),
    ToolMetadata(
        name="browser_click",
        description="Click an element on the current browser page using a CSS selector",
        risk_level=RiskLevel.MEDIUM, reversible=False, reversible_notes=None,
        requires_confirmation=False, conditional_confirmation_rules=[],
        data_egress=False, egress_type="none", network_behavior="Click action on page",
        path_scope_required=False, max_files_without_confirmation=None,
        max_total_bytes_without_confirmation=None, overwrite_policy="allow",
        secret_scan_required=False, requires_diff_preview=False,
        dry_run_supported=True, undo_supported=False, atomic=True,
        requires_screenshot=False, can_indirectly_execute_code=False,
        code_execution_mitigations=["URL blocklist; no file:// URLs"],
        platforms=ALL_PLATFORMS, domain="browser", batchable=False, idempotent=False,
    ),
    ToolMetadata(
        name="browser_type_text",
        description="Type text into an input field on the current browser page",
        risk_level=RiskLevel.MEDIUM, reversible=False, reversible_notes=None,
        requires_confirmation=False, conditional_confirmation_rules=[],
        data_egress=False, egress_type="none", network_behavior="Text input on page",
        path_scope_required=False, max_files_without_confirmation=None,
        max_total_bytes_without_confirmation=None, overwrite_policy="allow",
        secret_scan_required=True, requires_diff_preview=False,
        dry_run_supported=True, undo_supported=False, atomic=True,
        requires_screenshot=False, can_indirectly_execute_code=False,
        code_execution_mitigations=None, platforms=ALL_PLATFORMS,
        domain="browser", batchable=False, idempotent=False,
    ),
    ToolMetadata(
        name="browser_fill_form",
        description="Fill multiple form fields on the current browser page",
        risk_level=RiskLevel.MEDIUM, reversible=False, reversible_notes=None,
        requires_confirmation=False, conditional_confirmation_rules=[],
        data_egress=False, egress_type="none", network_behavior="Form input on page",
        path_scope_required=False, max_files_without_confirmation=None,
        max_total_bytes_without_confirmation=None, overwrite_policy="allow",
        secret_scan_required=True, requires_diff_preview=False,
        dry_run_supported=True, undo_supported=False, atomic=False,
        requires_screenshot=False, can_indirectly_execute_code=False,
        code_execution_mitigations=None, platforms=ALL_PLATFORMS,
        domain="browser", batchable=False, idempotent=False,
    ),
    ToolMetadata(
        name="browser_screenshot",
        description="Take a screenshot of the current browser page",
        risk_level=RiskLevel.LOW, reversible=True, reversible_notes=None,
        requires_confirmation=False, conditional_confirmation_rules=[],
        data_egress=False, egress_type="none", network_behavior=None,
        path_scope_required=False, max_files_without_confirmation=None,
        max_total_bytes_without_confirmation=None, overwrite_policy="allow",
        secret_scan_required=False, requires_diff_preview=False,
        dry_run_supported=True, undo_supported=True, atomic=True,
        requires_screenshot=True, can_indirectly_execute_code=False,
        code_execution_mitigations=None, platforms=ALL_PLATFORMS,
        domain="browser", batchable=False, idempotent=True,
    ),
    ToolMetadata(
        name="browser_wait_for_element",
        description="Wait for a CSS selector to appear/become visible on the page",
        risk_level=RiskLevel.LOW, reversible=True, reversible_notes=None,
        requires_confirmation=False, conditional_confirmation_rules=[],
        data_egress=False, egress_type="none", network_behavior=None,
        path_scope_required=False, max_files_without_confirmation=None,
        max_total_bytes_without_confirmation=None, overwrite_policy="allow",
        secret_scan_required=False, requires_diff_preview=False,
        dry_run_supported=True, undo_supported=False, atomic=True,
        requires_screenshot=False, can_indirectly_execute_code=False,
        code_execution_mitigations=None, platforms=ALL_PLATFORMS,
        domain="browser", batchable=False, idempotent=True,
    ),
    ToolMetadata(
        name="browser_scroll",
        description="Scroll the current browser page up, down, to top, or to bottom",
        risk_level=RiskLevel.LOW, reversible=True, reversible_notes=None,
        requires_confirmation=False, conditional_confirmation_rules=[],
        data_egress=False, egress_type="none", network_behavior=None,
        path_scope_required=False, max_files_without_confirmation=None,
        max_total_bytes_without_confirmation=None, overwrite_policy="allow",
        secret_scan_required=False, requires_diff_preview=False,
        dry_run_supported=True, undo_supported=False, atomic=True,
        requires_screenshot=False, can_indirectly_execute_code=False,
        code_execution_mitigations=None, platforms=ALL_PLATFORMS,
        domain="browser", batchable=False, idempotent=False,
    ),
    ToolMetadata(
        name="browser_go_back",
        description="Navigate back to the previous page in the browser",
        risk_level=RiskLevel.LOW, reversible=True, reversible_notes=None,
        requires_confirmation=False, conditional_confirmation_rules=[],
        data_egress=False, egress_type="none", network_behavior=None,
        path_scope_required=False, max_files_without_confirmation=None,
        max_total_bytes_without_confirmation=None, overwrite_policy="allow",
        secret_scan_required=False, requires_diff_preview=False,
        dry_run_supported=True, undo_supported=False, atomic=True,
        requires_screenshot=False, can_indirectly_execute_code=False,
        code_execution_mitigations=None, platforms=ALL_PLATFORMS,
        domain="browser", batchable=False, idempotent=False,
    ),
    ToolMetadata(
        name="browser_get_page_source",
        description="Get the full HTML source of the current browser page",
        risk_level=RiskLevel.LOW, reversible=True, reversible_notes=None,
        requires_confirmation=False, conditional_confirmation_rules=[],
        data_egress=True, egress_type="cloud_content",
        network_behavior="Page HTML excerpt optionally sent to LLM",
        path_scope_required=False, max_files_without_confirmation=None,
        max_total_bytes_without_confirmation=None, overwrite_policy="allow",
        secret_scan_required=False, requires_diff_preview=False,
        dry_run_supported=True, undo_supported=False, atomic=True,
        requires_screenshot=False, can_indirectly_execute_code=False,
        code_execution_mitigations=None, platforms=ALL_PLATFORMS,
        domain="browser", batchable=False, idempotent=True,
    ),
    ToolMetadata(
        name="browser_get_structured_data",
        description="Extract tables and lists from the current browser page as structured data",
        risk_level=RiskLevel.LOW, reversible=True, reversible_notes=None,
        requires_confirmation=False, conditional_confirmation_rules=[],
        data_egress=True, egress_type="cloud_content",
        network_behavior="Structured page data optionally sent to LLM",
        path_scope_required=False, max_files_without_confirmation=None,
        max_total_bytes_without_confirmation=None, overwrite_policy="allow",
        secret_scan_required=False, requires_diff_preview=False,
        dry_run_supported=True, undo_supported=False, atomic=True,
        requires_screenshot=False, can_indirectly_execute_code=False,
        code_execution_mitigations=None, platforms=ALL_PLATFORMS,
        domain="browser", batchable=False, idempotent=True,
    ),
    ToolMetadata(
        name="send_whatsapp_message",
        description="Send a WhatsApp text message via Meta Cloud API",
        risk_level=RiskLevel.MEDIUM, reversible=False, reversible_notes=None,
        requires_confirmation=True,
        conditional_confirmation_rules=[
            "Always: show recipient number and message preview before sending",
        ],
        data_egress=True, egress_type="outbound_api", network_behavior="outbound",
        path_scope_required=False, max_files_without_confirmation=None,
        max_total_bytes_without_confirmation=None, overwrite_policy="allow",
        secret_scan_required=True, requires_diff_preview=False,
        dry_run_supported=True, undo_supported=False, atomic=True,
        requires_screenshot=False, can_indirectly_execute_code=False,
        code_execution_mitigations=None, platforms=ALL_PLATFORMS,
        domain="messaging", batchable=False, idempotent=False,
    ),
    # ── Vision tools ─────────────────────────────────────────────────────────
    ToolMetadata(
        name="analyze_image",
        description="Analyze any image file using AI vision — describe contents, read text, identify objects",
        risk_level=RiskLevel.LOW, reversible=True, reversible_notes=None,
        requires_confirmation=False, conditional_confirmation_rules=[],
        data_egress=True, egress_type="outbound_api", network_behavior="outbound",
        path_scope_required=False, max_files_without_confirmation=None,
        max_total_bytes_without_confirmation=None, overwrite_policy="allow",
        secret_scan_required=False, requires_diff_preview=False,
        dry_run_supported=True, undo_supported=False, atomic=True,
        requires_screenshot=False, can_indirectly_execute_code=False,
        code_execution_mitigations=None, platforms=ALL_PLATFORMS,
        domain="vision", batchable=False, idempotent=True,
    ),
    ToolMetadata(
        name="capture_and_analyze",
        description="Take a screenshot of the current browser page and analyze it with AI vision",
        risk_level=RiskLevel.LOW, reversible=True, reversible_notes=None,
        requires_confirmation=False, conditional_confirmation_rules=[],
        data_egress=True, egress_type="outbound_api", network_behavior="outbound",
        path_scope_required=False, max_files_without_confirmation=None,
        max_total_bytes_without_confirmation=None, overwrite_policy="allow",
        secret_scan_required=False, requires_diff_preview=False,
        dry_run_supported=True, undo_supported=False, atomic=True,
        requires_screenshot=True, can_indirectly_execute_code=False,
        code_execution_mitigations=None, platforms=ALL_PLATFORMS,
        domain="vision", batchable=False, idempotent=True,
    ),
    # ── Coding Agent tools ────────────────────────────────────────────────────
    ToolMetadata(
        name="generate_code",
        description="Generate production-quality code from a natural language description",
        risk_level=RiskLevel.MEDIUM, reversible=True, reversible_notes="File write reversible",
        requires_confirmation=False,
        conditional_confirmation_rules=["If output_path specified: confirm before overwriting existing file"],
        data_egress=True, egress_type="outbound_api", network_behavior="outbound",
        path_scope_required=False, max_files_without_confirmation=None,
        max_total_bytes_without_confirmation=None, overwrite_policy="confirm",
        secret_scan_required=False, requires_diff_preview=True,
        dry_run_supported=True, undo_supported=True, atomic=True,
        requires_screenshot=False, can_indirectly_execute_code=True,
        code_execution_mitigations=["Generated code is not executed automatically"],
        platforms=ALL_PLATFORMS, domain="code", batchable=False, idempotent=False,
    ),
    ToolMetadata(
        name="explain_code",
        description="Read a source file and produce a detailed AI explanation of what the code does",
        risk_level=RiskLevel.LOW, reversible=True, reversible_notes=None,
        requires_confirmation=False, conditional_confirmation_rules=[],
        data_egress=True, egress_type="outbound_api", network_behavior="outbound",
        path_scope_required=True, max_files_without_confirmation=None,
        max_total_bytes_without_confirmation=None, overwrite_policy="allow",
        secret_scan_required=True, requires_diff_preview=False,
        dry_run_supported=True, undo_supported=False, atomic=True,
        requires_screenshot=False, can_indirectly_execute_code=False,
        code_execution_mitigations=None, platforms=ALL_PLATFORMS,
        domain="code", batchable=False, idempotent=True,
    ),
    ToolMetadata(
        name="refactor_code",
        description="Refactor existing source code according to natural language instructions",
        risk_level=RiskLevel.HIGH, reversible=False,
        reversible_notes="Overwrites file — use version control to recover original",
        requires_confirmation=True,
        conditional_confirmation_rules=["Always: show diff preview before saving"],
        data_egress=True, egress_type="outbound_api", network_behavior="outbound",
        path_scope_required=True, max_files_without_confirmation=None,
        max_total_bytes_without_confirmation=None, overwrite_policy="confirm",
        secret_scan_required=True, requires_diff_preview=True,
        dry_run_supported=True, undo_supported=False, atomic=True,
        requires_screenshot=False, can_indirectly_execute_code=False,
        code_execution_mitigations=None, platforms=ALL_PLATFORMS,
        domain="code", batchable=False, idempotent=False,
    ),
    ToolMetadata(
        name="write_tests",
        description="Generate a comprehensive test suite for a source file using AI",
        risk_level=RiskLevel.LOW, reversible=True, reversible_notes="Creates new test file",
        requires_confirmation=False, conditional_confirmation_rules=[],
        data_egress=True, egress_type="outbound_api", network_behavior="outbound",
        path_scope_required=True, max_files_without_confirmation=None,
        max_total_bytes_without_confirmation=None, overwrite_policy="allow",
        secret_scan_required=True, requires_diff_preview=False,
        dry_run_supported=True, undo_supported=True, atomic=True,
        requires_screenshot=False, can_indirectly_execute_code=False,
        code_execution_mitigations=None, platforms=ALL_PLATFORMS,
        domain="code", batchable=False, idempotent=False,
    ),
    ToolMetadata(
        name="analyze_code_quality",
        description="Perform a comprehensive AI code quality review with scores, issues, and recommendations",
        risk_level=RiskLevel.LOW, reversible=True, reversible_notes=None,
        requires_confirmation=False, conditional_confirmation_rules=[],
        data_egress=True, egress_type="outbound_api", network_behavior="outbound",
        path_scope_required=True, max_files_without_confirmation=None,
        max_total_bytes_without_confirmation=None, overwrite_policy="allow",
        secret_scan_required=True, requires_diff_preview=False,
        dry_run_supported=True, undo_supported=False, atomic=True,
        requires_screenshot=False, can_indirectly_execute_code=False,
        code_execution_mitigations=None, platforms=ALL_PLATFORMS,
        domain="code", batchable=False, idempotent=True,
    ),
    # ── Sandboxed code execution (Gap #1) ────────────────────────────────────
    ToolMetadata(
        name="run_code",
        description="Execute code in an isolated sandbox (Python/JS/Bash) with clean environment, no credentials leaked",
        risk_level=RiskLevel.HIGH, reversible=False, reversible_notes="Side-effects of code execution may be irreversible",
        requires_confirmation=True, conditional_confirmation_rules=["Always require confirmation before executing code"],
        data_egress=False, egress_type="none", network_behavior="none",
        path_scope_required=False, max_files_without_confirmation=None,
        max_total_bytes_without_confirmation=None, overwrite_policy="allow",
        secret_scan_required=True, requires_diff_preview=True,
        dry_run_supported=True, undo_supported=False, atomic=False,
        requires_screenshot=False, can_indirectly_execute_code=True,
        code_execution_mitigations=["sandbox_env", "no_network", "scrubbed_env_vars", "timeout_enforced"],
        platforms=ALL_PLATFORMS,
        domain="code", batchable=False, idempotent=False,
    ),
    # ── Google Calendar tools ─────────────────────────────────────────────────
    ToolMetadata(
        name="list_calendar_events",
        description="List upcoming Google Calendar events",
        risk_level=RiskLevel.LOW, reversible=True, reversible_notes=None,
        requires_confirmation=False, conditional_confirmation_rules=[],
        data_egress=True, egress_type="outbound_api",
        network_behavior="Reads event metadata from Google Calendar API",
        path_scope_required=False, max_files_without_confirmation=None,
        max_total_bytes_without_confirmation=None, overwrite_policy="allow",
        secret_scan_required=False, requires_diff_preview=False,
        dry_run_supported=True, undo_supported=False, atomic=True,
        requires_screenshot=False, can_indirectly_execute_code=False,
        code_execution_mitigations=None, platforms=ALL_PLATFORMS,
        domain="calendar", batchable=False, idempotent=True,
    ),
    ToolMetadata(
        name="create_calendar_event",
        description="Create a new event on Google Calendar",
        risk_level=RiskLevel.MEDIUM, reversible=True,
        reversible_notes="Event can be deleted from Calendar to undo",
        requires_confirmation=True,
        conditional_confirmation_rules=["Always: show event title, time, and description before creating"],
        data_egress=True, egress_type="outbound_api",
        network_behavior="Writes event to Google Calendar API",
        path_scope_required=False, max_files_without_confirmation=None,
        max_total_bytes_without_confirmation=None, overwrite_policy="allow",
        secret_scan_required=False, requires_diff_preview=True,
        dry_run_supported=True, undo_supported=False, atomic=True,
        requires_screenshot=False, can_indirectly_execute_code=False,
        code_execution_mitigations=None, platforms=ALL_PLATFORMS,
        domain="calendar", batchable=False, idempotent=False,
    ),
    ToolMetadata(
        name="delete_calendar_event",
        description="Delete a Google Calendar event by event ID",
        risk_level=RiskLevel.HIGH, reversible=False,
        reversible_notes="Deletion is permanent unless recovered from Trash in Google Calendar",
        requires_confirmation=True,
        conditional_confirmation_rules=["Always: show event ID and title before deleting"],
        data_egress=False, egress_type="outbound_api",
        network_behavior="Deletes event from Google Calendar API",
        path_scope_required=False, max_files_without_confirmation=None,
        max_total_bytes_without_confirmation=None, overwrite_policy="allow",
        secret_scan_required=False, requires_diff_preview=False,
        dry_run_supported=True, undo_supported=False, atomic=True,
        requires_screenshot=False, can_indirectly_execute_code=False,
        code_execution_mitigations=None, platforms=ALL_PLATFORMS,
        domain="calendar", batchable=False, idempotent=False,
    ),
    # ── Desktop tools (via local bridge) ─────────────────────────────────────
    ToolMetadata(
        name="desktop_screenshot",
        description="Capture a screenshot of the user's local desktop",
        risk_level=RiskLevel.LOW, reversible=True, reversible_notes=None,
        requires_confirmation=False, conditional_confirmation_rules=[],
        data_egress=True, egress_type="cloud_content",
        network_behavior="Screenshot image optionally sent to LLM for vision analysis",
        path_scope_required=False, max_files_without_confirmation=None,
        max_total_bytes_without_confirmation=None, overwrite_policy="allow",
        secret_scan_required=False, requires_diff_preview=False,
        dry_run_supported=True, undo_supported=False, atomic=True,
        requires_screenshot=True, can_indirectly_execute_code=False,
        code_execution_mitigations=None, platforms=ALL_PLATFORMS,
        domain="desktop", batchable=False, idempotent=True,
    ),
    ToolMetadata(
        name="desktop_click",
        description="Click at pixel coordinates or on a described UI element on the local desktop",
        risk_level=RiskLevel.MEDIUM, reversible=False, reversible_notes=None,
        requires_confirmation=False,
        conditional_confirmation_rules=["Destructive UI action (delete/format): confirm"],
        data_egress=False, egress_type="none", network_behavior=None,
        path_scope_required=False, max_files_without_confirmation=None,
        max_total_bytes_without_confirmation=None, overwrite_policy="allow",
        secret_scan_required=False, requires_diff_preview=False,
        dry_run_supported=True, undo_supported=False, atomic=True,
        requires_screenshot=True, can_indirectly_execute_code=True,
        code_execution_mitigations=["Vision-grounded coordinate derivation; no arbitrary code"],
        platforms=ALL_PLATFORMS, domain="desktop", batchable=False, idempotent=False,
    ),
    ToolMetadata(
        name="desktop_double_click",
        description="Double-click at coordinates or on a described element on the local desktop",
        risk_level=RiskLevel.MEDIUM, reversible=False, reversible_notes=None,
        requires_confirmation=False, conditional_confirmation_rules=[],
        data_egress=False, egress_type="none", network_behavior=None,
        path_scope_required=False, max_files_without_confirmation=None,
        max_total_bytes_without_confirmation=None, overwrite_policy="allow",
        secret_scan_required=False, requires_diff_preview=False,
        dry_run_supported=True, undo_supported=False, atomic=True,
        requires_screenshot=True, can_indirectly_execute_code=True,
        code_execution_mitigations=["Vision-grounded coordinate derivation"],
        platforms=ALL_PLATFORMS, domain="desktop", batchable=False, idempotent=False,
    ),
    ToolMetadata(
        name="desktop_right_click",
        description="Right-click at coordinates or on a described element on the local desktop",
        risk_level=RiskLevel.LOW, reversible=False, reversible_notes=None,
        requires_confirmation=False, conditional_confirmation_rules=[],
        data_egress=False, egress_type="none", network_behavior=None,
        path_scope_required=False, max_files_without_confirmation=None,
        max_total_bytes_without_confirmation=None, overwrite_policy="allow",
        secret_scan_required=False, requires_diff_preview=False,
        dry_run_supported=True, undo_supported=False, atomic=True,
        requires_screenshot=True, can_indirectly_execute_code=False,
        code_execution_mitigations=None, platforms=ALL_PLATFORMS,
        domain="desktop", batchable=False, idempotent=False,
    ),
    ToolMetadata(
        name="desktop_type_text",
        description="Type text at the current cursor position on the local desktop",
        risk_level=RiskLevel.MEDIUM, reversible=False, reversible_notes=None,
        requires_confirmation=False,
        conditional_confirmation_rules=["Text contains secret pattern: HALT"],
        data_egress=False, egress_type="none", network_behavior=None,
        path_scope_required=False, max_files_without_confirmation=None,
        max_total_bytes_without_confirmation=None, overwrite_policy="allow",
        secret_scan_required=True, requires_diff_preview=False,
        dry_run_supported=True, undo_supported=False, atomic=False,
        requires_screenshot=False, can_indirectly_execute_code=False,
        code_execution_mitigations=None, platforms=ALL_PLATFORMS,
        domain="desktop", batchable=False, idempotent=False,
    ),
    ToolMetadata(
        name="desktop_key",
        description="Press a keyboard shortcut or key combination on the local desktop",
        risk_level=RiskLevel.MEDIUM, reversible=False, reversible_notes=None,
        requires_confirmation=False,
        conditional_confirmation_rules=["Destructive key (delete, format, shutdown): confirm"],
        data_egress=False, egress_type="none", network_behavior=None,
        path_scope_required=False, max_files_without_confirmation=None,
        max_total_bytes_without_confirmation=None, overwrite_policy="allow",
        secret_scan_required=False, requires_diff_preview=False,
        dry_run_supported=True, undo_supported=False, atomic=True,
        requires_screenshot=False, can_indirectly_execute_code=True,
        code_execution_mitigations=["Blocklist: ctrl+alt+del, shutdown combos require confirm"],
        platforms=ALL_PLATFORMS, domain="desktop", batchable=False, idempotent=False,
    ),
    ToolMetadata(
        name="desktop_scroll",
        description="Scroll the mouse wheel at a position on the local desktop",
        risk_level=RiskLevel.LOW, reversible=True, reversible_notes=None,
        requires_confirmation=False, conditional_confirmation_rules=[],
        data_egress=False, egress_type="none", network_behavior=None,
        path_scope_required=False, max_files_without_confirmation=None,
        max_total_bytes_without_confirmation=None, overwrite_policy="allow",
        secret_scan_required=False, requires_diff_preview=False,
        dry_run_supported=True, undo_supported=False, atomic=True,
        requires_screenshot=False, can_indirectly_execute_code=False,
        code_execution_mitigations=None, platforms=ALL_PLATFORMS,
        domain="desktop", batchable=False, idempotent=False,
    ),
    ToolMetadata(
        name="desktop_move_mouse",
        description="Move the mouse cursor to pixel coordinates on the local desktop",
        risk_level=RiskLevel.LOW, reversible=True, reversible_notes=None,
        requires_confirmation=False, conditional_confirmation_rules=[],
        data_egress=False, egress_type="none", network_behavior=None,
        path_scope_required=False, max_files_without_confirmation=None,
        max_total_bytes_without_confirmation=None, overwrite_policy="allow",
        secret_scan_required=False, requires_diff_preview=False,
        dry_run_supported=True, undo_supported=False, atomic=True,
        requires_screenshot=False, can_indirectly_execute_code=False,
        code_execution_mitigations=None, platforms=ALL_PLATFORMS,
        domain="desktop", batchable=False, idempotent=True,
    ),
    ToolMetadata(
        name="desktop_drag",
        description="Click-and-drag from one position to another on the local desktop",
        risk_level=RiskLevel.MEDIUM, reversible=False, reversible_notes=None,
        requires_confirmation=False, conditional_confirmation_rules=[],
        data_egress=False, egress_type="none", network_behavior=None,
        path_scope_required=False, max_files_without_confirmation=None,
        max_total_bytes_without_confirmation=None, overwrite_policy="allow",
        secret_scan_required=False, requires_diff_preview=False,
        dry_run_supported=True, undo_supported=False, atomic=True,
        requires_screenshot=False, can_indirectly_execute_code=False,
        code_execution_mitigations=None, platforms=ALL_PLATFORMS,
        domain="desktop", batchable=False, idempotent=False,
    ),
    ToolMetadata(
        name="desktop_find_and_click",
        description="Use AI vision to find a described UI element on-screen and click it",
        risk_level=RiskLevel.HIGH, reversible=False, reversible_notes=None,
        requires_confirmation=False,
        conditional_confirmation_rules=["Destructive UI action (delete/format): confirm"],
        data_egress=True, egress_type="cloud_content",
        network_behavior="Screenshot sent to LLM vision model to locate element",
        path_scope_required=False, max_files_without_confirmation=None,
        max_total_bytes_without_confirmation=None, overwrite_policy="allow",
        secret_scan_required=False, requires_diff_preview=False,
        dry_run_supported=True, undo_supported=False, atomic=True,
        requires_screenshot=True, can_indirectly_execute_code=True,
        code_execution_mitigations=["Vision-grounded; LLM cannot issue arbitrary commands"],
        platforms=ALL_PLATFORMS, domain="desktop", batchable=False, idempotent=False,
    ),
    ToolMetadata(
        name="desktop_read_screen",
        description="Screenshot the local desktop and extract all visible text via AI OCR",
        risk_level=RiskLevel.LOW, reversible=True, reversible_notes=None,
        requires_confirmation=False,
        conditional_confirmation_rules=["Cloud mode + screen content: show data-egress notice"],
        data_egress=True, egress_type="cloud_content",
        network_behavior="Screenshot + extracted text sent to LLM",
        path_scope_required=False, max_files_without_confirmation=None,
        max_total_bytes_without_confirmation=None, overwrite_policy="allow",
        secret_scan_required=False, requires_diff_preview=False,
        dry_run_supported=True, undo_supported=False, atomic=True,
        requires_screenshot=True, can_indirectly_execute_code=False,
        code_execution_mitigations=None, platforms=ALL_PLATFORMS,
        domain="desktop", batchable=False, idempotent=True,
    ),
    # ── Research Agent tools ──────────────────────────────────────────────────
    ToolMetadata(
        name="research_topic",
        description="Perform deep multi-source web research on a topic and synthesize a structured report",
        risk_level=RiskLevel.LOW, reversible=True, reversible_notes=None,
        requires_confirmation=False, conditional_confirmation_rules=[],
        data_egress=True, egress_type="outbound_api", network_behavior="outbound",
        path_scope_required=False, max_files_without_confirmation=None,
        max_total_bytes_without_confirmation=None, overwrite_policy="allow",
        secret_scan_required=False, requires_diff_preview=False,
        dry_run_supported=True, undo_supported=False, atomic=False,
        requires_screenshot=False, can_indirectly_execute_code=False,
        code_execution_mitigations=None, platforms=ALL_PLATFORMS,
        domain="research", batchable=False, idempotent=True,
    ),
    ToolMetadata(
        name="summarize_url",
        description="Navigate to a URL and produce a concise AI summary of its content",
        risk_level=RiskLevel.LOW, reversible=True, reversible_notes=None,
        requires_confirmation=False, conditional_confirmation_rules=[],
        data_egress=True, egress_type="outbound_api", network_behavior="outbound",
        path_scope_required=False, max_files_without_confirmation=None,
        max_total_bytes_without_confirmation=None, overwrite_policy="allow",
        secret_scan_required=False, requires_diff_preview=False,
        dry_run_supported=True, undo_supported=False, atomic=True,
        requires_screenshot=False, can_indirectly_execute_code=False,
        code_execution_mitigations=None, platforms=ALL_PLATFORMS,
        domain="research", batchable=False, idempotent=True,
    ),
    # ── Digital Employee tools ────────────────────────────────────────────────
    ToolMetadata(
        name="cleanup_temp_files",
        description="Find and remove temporary files (cache, .pyc, /tmp) to free disk space",
        risk_level=RiskLevel.HIGH, reversible=False,
        reversible_notes="Deleted files cannot be recovered — dry_run=True for preview",
        requires_confirmation=True,
        conditional_confirmation_rules=[
            "Always confirm before deleting; dry_run first then prompt for approval",
            "Skip confirmation if dry_run=True",
        ],
        data_egress=False, egress_type="none", network_behavior=None,
        path_scope_required=False, max_files_without_confirmation=None,
        max_total_bytes_without_confirmation=None, overwrite_policy="allow",
        secret_scan_required=False, requires_diff_preview=True,
        dry_run_supported=True, undo_supported=False, atomic=False,
        requires_screenshot=False, can_indirectly_execute_code=False,
        code_execution_mitigations=None, platforms=ALL_PLATFORMS,
        domain="system", batchable=False, idempotent=False,
    ),
    ToolMetadata(
        name="open_web_app",
        description="Open any web application by name in the browser (WhatsApp, Instagram, LinkedIn, TikTok, Gmail, YouTube, etc.)",
        risk_level=RiskLevel.MEDIUM, reversible=True, reversible_notes=None,
        requires_confirmation=False,
        conditional_confirmation_rules=[
            "Actions that post/send/publish: confirm before interacting with the page",
        ],
        data_egress=True, egress_type="browser",
        network_behavior="Opens browser to target web app URL",
        path_scope_required=False, max_files_without_confirmation=None,
        max_total_bytes_without_confirmation=None, overwrite_policy="allow",
        secret_scan_required=False, requires_diff_preview=False,
        dry_run_supported=True, undo_supported=False, atomic=True,
        requires_screenshot=False, can_indirectly_execute_code=False,
        code_execution_mitigations=None, platforms=ALL_PLATFORMS,
        domain="browser", batchable=False, idempotent=True,
    ),
    ToolMetadata(
        name="navigate_web_app",
        description="Navigate to a specific section of a web app and optionally perform a task (e.g. LinkedIn jobs, Gmail compose, TikTok upload)",
        risk_level=RiskLevel.MEDIUM, reversible=True, reversible_notes=None,
        requires_confirmation=False,
        conditional_confirmation_rules=[
            "If task involves sending a message or publishing: confirm first",
        ],
        data_egress=True, egress_type="browser",
        network_behavior="Opens browser to specific app section URL",
        path_scope_required=False, max_files_without_confirmation=None,
        max_total_bytes_without_confirmation=None, overwrite_policy="allow",
        secret_scan_required=False, requires_diff_preview=False,
        dry_run_supported=True, undo_supported=False, atomic=True,
        requires_screenshot=False, can_indirectly_execute_code=False,
        code_execution_mitigations=None, platforms=ALL_PLATFORMS,
        domain="browser", batchable=False, idempotent=True,
    ),
    ToolMetadata(
        name="find_installed_apps",
        description="Search for installed applications on this computer by name",
        risk_level=RiskLevel.LOW, reversible=True, reversible_notes=None,
        requires_confirmation=False, conditional_confirmation_rules=[],
        data_egress=False, egress_type="none", network_behavior=None,
        path_scope_required=False, max_files_without_confirmation=None,
        max_total_bytes_without_confirmation=None, overwrite_policy="allow",
        secret_scan_required=False, requires_diff_preview=False,
        dry_run_supported=True, undo_supported=False, atomic=True,
        requires_screenshot=False, can_indirectly_execute_code=False,
        code_execution_mitigations=None, platforms=ALL_PLATFORMS,
        domain="app", batchable=False, idempotent=True,
    ),
    ToolMetadata(
        name="list_available_web_apps",
        description="Return the full list of web apps Arix can navigate to",
        risk_level=RiskLevel.LOW, reversible=True, reversible_notes=None,
        requires_confirmation=False, conditional_confirmation_rules=[],
        data_egress=False, egress_type="none", network_behavior=None,
        path_scope_required=False, max_files_without_confirmation=None,
        max_total_bytes_without_confirmation=None, overwrite_policy="allow",
        secret_scan_required=False, requires_diff_preview=False,
        dry_run_supported=True, undo_supported=False, atomic=True,
        requires_screenshot=False, can_indirectly_execute_code=False,
        code_execution_mitigations=None, platforms=ALL_PLATFORMS,
        domain="browser", batchable=False, idempotent=True,
    ),
    # ── Gmail tools ───────────────────────────────────────────────────────────
    ToolMetadata(
        name="gmail_list_emails",
        description="List emails from Gmail inbox or any label/folder",
        risk_level=RiskLevel.LOW, reversible=True, reversible_notes=None,
        requires_confirmation=False, conditional_confirmation_rules=[],
        data_egress=True, egress_type="cloud_content",
        network_behavior="Email metadata fetched from Gmail API",
        path_scope_required=False, max_files_without_confirmation=None,
        max_total_bytes_without_confirmation=None, overwrite_policy="allow",
        secret_scan_required=False, requires_diff_preview=False,
        dry_run_supported=True, undo_supported=False, atomic=True,
        requires_screenshot=False, can_indirectly_execute_code=False,
        code_execution_mitigations=None, platforms=ALL_PLATFORMS,
        domain="gmail", batchable=False, idempotent=True,
    ),
    ToolMetadata(
        name="gmail_read_email",
        description="Read the full body and headers of a Gmail message by ID",
        risk_level=RiskLevel.LOW, reversible=True, reversible_notes=None,
        requires_confirmation=False,
        conditional_confirmation_rules=["Cloud mode: show data-egress notice for email body"],
        data_egress=True, egress_type="cloud_content",
        network_behavior="Email body sent to LLM if summarized",
        path_scope_required=False, max_files_without_confirmation=None,
        max_total_bytes_without_confirmation=None, overwrite_policy="allow",
        secret_scan_required=True, requires_diff_preview=False,
        dry_run_supported=True, undo_supported=False, atomic=True,
        requires_screenshot=False, can_indirectly_execute_code=False,
        code_execution_mitigations=None, platforms=ALL_PLATFORMS,
        domain="gmail", batchable=False, idempotent=True,
    ),
    ToolMetadata(
        name="gmail_send_email",
        description="Compose and send an email via Gmail",
        risk_level=RiskLevel.HIGH, reversible=False,
        reversible_notes="Sent emails cannot be unsent",
        requires_confirmation=True,
        conditional_confirmation_rules=["Always confirm before sending"],
        data_egress=True, egress_type="outbound_api",
        network_behavior="Email sent via Gmail API",
        path_scope_required=False, max_files_without_confirmation=None,
        max_total_bytes_without_confirmation=None, overwrite_policy="allow",
        secret_scan_required=True, requires_diff_preview=True,
        dry_run_supported=True, undo_supported=False, atomic=True,
        requires_screenshot=False, can_indirectly_execute_code=False,
        code_execution_mitigations=None, platforms=ALL_PLATFORMS,
        domain="gmail", batchable=False, idempotent=False,
    ),
    ToolMetadata(
        name="gmail_search_emails",
        description="Search Gmail using Gmail query syntax (e.g. 'from:boss@co.com is:unread')",
        risk_level=RiskLevel.LOW, reversible=True, reversible_notes=None,
        requires_confirmation=False, conditional_confirmation_rules=[],
        data_egress=True, egress_type="cloud_content",
        network_behavior="Search results fetched from Gmail API",
        path_scope_required=False, max_files_without_confirmation=None,
        max_total_bytes_without_confirmation=None, overwrite_policy="allow",
        secret_scan_required=False, requires_diff_preview=False,
        dry_run_supported=True, undo_supported=False, atomic=True,
        requires_screenshot=False, can_indirectly_execute_code=False,
        code_execution_mitigations=None, platforms=ALL_PLATFORMS,
        domain="gmail", batchable=False, idempotent=True,
    ),
    ToolMetadata(
        name="gmail_delete_email",
        description="Permanently delete a Gmail message by ID",
        risk_level=RiskLevel.HIGH, reversible=False,
        reversible_notes="Deleted emails go to Trash — may be recoverable within 30 days",
        requires_confirmation=True,
        conditional_confirmation_rules=["Always confirm before deleting"],
        data_egress=False, egress_type="none", network_behavior=None,
        path_scope_required=False, max_files_without_confirmation=None,
        max_total_bytes_without_confirmation=None, overwrite_policy="allow",
        secret_scan_required=False, requires_diff_preview=False,
        dry_run_supported=True, undo_supported=False, atomic=True,
        requires_screenshot=False, can_indirectly_execute_code=False,
        code_execution_mitigations=None, platforms=ALL_PLATFORMS,
        domain="gmail", batchable=False, idempotent=False,
    ),
    # ── Google Drive tools ────────────────────────────────────────────────────
    ToolMetadata(
        name="drive_list_files",
        description="List files and folders in a Google Drive folder",
        risk_level=RiskLevel.LOW, reversible=True, reversible_notes=None,
        requires_confirmation=False, conditional_confirmation_rules=[],
        data_egress=True, egress_type="cloud_content",
        network_behavior="File listing fetched from Drive API",
        path_scope_required=False, max_files_without_confirmation=None,
        max_total_bytes_without_confirmation=None, overwrite_policy="allow",
        secret_scan_required=False, requires_diff_preview=False,
        dry_run_supported=True, undo_supported=False, atomic=True,
        requires_screenshot=False, can_indirectly_execute_code=False,
        code_execution_mitigations=None, platforms=ALL_PLATFORMS,
        domain="drive", batchable=False, idempotent=True,
    ),
    ToolMetadata(
        name="drive_search_files",
        description="Search for files in Google Drive by name",
        risk_level=RiskLevel.LOW, reversible=True, reversible_notes=None,
        requires_confirmation=False, conditional_confirmation_rules=[],
        data_egress=True, egress_type="cloud_content",
        network_behavior="Search results fetched from Drive API",
        path_scope_required=False, max_files_without_confirmation=None,
        max_total_bytes_without_confirmation=None, overwrite_policy="allow",
        secret_scan_required=False, requires_diff_preview=False,
        dry_run_supported=True, undo_supported=False, atomic=True,
        requires_screenshot=False, can_indirectly_execute_code=False,
        code_execution_mitigations=None, platforms=ALL_PLATFORMS,
        domain="drive", batchable=False, idempotent=True,
    ),
    ToolMetadata(
        name="drive_read_file",
        description="Read the text content of a Google Drive file (Docs, Sheets, plain text)",
        risk_level=RiskLevel.LOW, reversible=True, reversible_notes=None,
        requires_confirmation=False,
        conditional_confirmation_rules=["Cloud mode: show data-egress notice"],
        data_egress=True, egress_type="cloud_content",
        network_behavior="File content fetched from Drive API",
        path_scope_required=False, max_files_without_confirmation=None,
        max_total_bytes_without_confirmation=None, overwrite_policy="allow",
        secret_scan_required=True, requires_diff_preview=False,
        dry_run_supported=True, undo_supported=False, atomic=True,
        requires_screenshot=False, can_indirectly_execute_code=False,
        code_execution_mitigations=None, platforms=ALL_PLATFORMS,
        domain="drive", batchable=False, idempotent=True,
    ),
    ToolMetadata(
        name="drive_upload_file",
        description="Upload a local file to Google Drive",
        risk_level=RiskLevel.MEDIUM, reversible=True,
        reversible_notes="File can be deleted from Drive manually",
        requires_confirmation=False,
        conditional_confirmation_rules=["File > 10 MB: confirm before upload"],
        data_egress=True, egress_type="outbound_api",
        network_behavior="Local file uploaded to Google Drive",
        path_scope_required=True, max_files_without_confirmation=1,
        max_total_bytes_without_confirmation=10_485_760, overwrite_policy="allow",
        secret_scan_required=True, requires_diff_preview=False,
        dry_run_supported=True, undo_supported=False, atomic=True,
        requires_screenshot=False, can_indirectly_execute_code=False,
        code_execution_mitigations=None, platforms=ALL_PLATFORMS,
        domain="drive", batchable=False, idempotent=False,
    ),
    # ── Notion tools ─────────────────────────────────────────────────────────
    ToolMetadata(
        name="notion_search", description="Search Notion pages and databases.",
        risk_level=RiskLevel.LOW, reversible=True, reversible_notes=None,
        requires_confirmation=False, conditional_confirmation_rules=[],
        data_egress=True, egress_type="cloud_metadata", network_behavior="read-only Notion API",
        path_scope_required=False, max_files_without_confirmation=None,
        max_total_bytes_without_confirmation=None, overwrite_policy="allow",
        secret_scan_required=False, requires_diff_preview=False,
        dry_run_supported=True, undo_supported=False, atomic=True,
        requires_screenshot=False, can_indirectly_execute_code=False,
        code_execution_mitigations=None, platforms=ALL_PLATFORMS,
        domain="notion", batchable=False, idempotent=True,
    ),
    ToolMetadata(
        name="notion_read_page", description="Read the content of a Notion page by ID.",
        risk_level=RiskLevel.LOW, reversible=True, reversible_notes=None,
        requires_confirmation=False, conditional_confirmation_rules=[],
        data_egress=True, egress_type="cloud_content", network_behavior="read-only Notion API",
        path_scope_required=False, max_files_without_confirmation=None,
        max_total_bytes_without_confirmation=None, overwrite_policy="allow",
        secret_scan_required=False, requires_diff_preview=False,
        dry_run_supported=True, undo_supported=False, atomic=True,
        requires_screenshot=False, can_indirectly_execute_code=False,
        code_execution_mitigations=None, platforms=ALL_PLATFORMS,
        domain="notion", batchable=False, idempotent=True,
    ),
    ToolMetadata(
        name="notion_create_page", description="Create a new Notion page with optional content.",
        risk_level=RiskLevel.MEDIUM, reversible=True, reversible_notes="Page can be deleted",
        requires_confirmation=False, conditional_confirmation_rules=[],
        data_egress=True, egress_type="cloud_content", network_behavior="write Notion API",
        path_scope_required=False, max_files_without_confirmation=None,
        max_total_bytes_without_confirmation=None, overwrite_policy="allow",
        secret_scan_required=False, requires_diff_preview=False,
        dry_run_supported=True, undo_supported=False, atomic=True,
        requires_screenshot=False, can_indirectly_execute_code=False,
        code_execution_mitigations=None, platforms=ALL_PLATFORMS,
        domain="notion", batchable=False, idempotent=False,
    ),
    ToolMetadata(
        name="notion_append_to_page", description="Append text content to an existing Notion page.",
        risk_level=RiskLevel.MEDIUM, reversible=True, reversible_notes="Blocks can be deleted",
        requires_confirmation=False, conditional_confirmation_rules=[],
        data_egress=True, egress_type="cloud_content", network_behavior="write Notion API",
        path_scope_required=False, max_files_without_confirmation=None,
        max_total_bytes_without_confirmation=None, overwrite_policy="allow",
        secret_scan_required=False, requires_diff_preview=False,
        dry_run_supported=True, undo_supported=False, atomic=True,
        requires_screenshot=False, can_indirectly_execute_code=False,
        code_execution_mitigations=None, platforms=ALL_PLATFORMS,
        domain="notion", batchable=False, idempotent=False,
    ),
    # ── Slack tools ───────────────────────────────────────────────────────────
    ToolMetadata(
        name="slack_list_channels", description="List all Slack channels in the workspace.",
        risk_level=RiskLevel.LOW, reversible=True, reversible_notes=None,
        requires_confirmation=False, conditional_confirmation_rules=[],
        data_egress=True, egress_type="cloud_metadata", network_behavior="read-only Slack API",
        path_scope_required=False, max_files_without_confirmation=None,
        max_total_bytes_without_confirmation=None, overwrite_policy="allow",
        secret_scan_required=False, requires_diff_preview=False,
        dry_run_supported=True, undo_supported=False, atomic=True,
        requires_screenshot=False, can_indirectly_execute_code=False,
        code_execution_mitigations=None, platforms=ALL_PLATFORMS,
        domain="slack", batchable=False, idempotent=True,
    ),
    ToolMetadata(
        name="slack_send_message", description="Send a message to a Slack channel or thread.",
        risk_level=RiskLevel.MEDIUM, reversible=False, reversible_notes=None,
        requires_confirmation=False, conditional_confirmation_rules=[],
        data_egress=True, egress_type="cloud_content", network_behavior="write Slack API",
        path_scope_required=False, max_files_without_confirmation=None,
        max_total_bytes_without_confirmation=None, overwrite_policy="allow",
        secret_scan_required=False, requires_diff_preview=False,
        dry_run_supported=True, undo_supported=False, atomic=True,
        requires_screenshot=False, can_indirectly_execute_code=False,
        code_execution_mitigations=None, platforms=ALL_PLATFORMS,
        domain="slack", batchable=False, idempotent=False,
    ),
    ToolMetadata(
        name="slack_get_messages", description="Get recent messages from a Slack channel.",
        risk_level=RiskLevel.LOW, reversible=True, reversible_notes=None,
        requires_confirmation=False, conditional_confirmation_rules=[],
        data_egress=True, egress_type="cloud_content", network_behavior="read-only Slack API",
        path_scope_required=False, max_files_without_confirmation=None,
        max_total_bytes_without_confirmation=None, overwrite_policy="allow",
        secret_scan_required=False, requires_diff_preview=False,
        dry_run_supported=True, undo_supported=False, atomic=True,
        requires_screenshot=False, can_indirectly_execute_code=False,
        code_execution_mitigations=None, platforms=ALL_PLATFORMS,
        domain="slack", batchable=False, idempotent=True,
    ),
    ToolMetadata(
        name="slack_search", description="Search Slack messages across all channels.",
        risk_level=RiskLevel.LOW, reversible=True, reversible_notes=None,
        requires_confirmation=False, conditional_confirmation_rules=[],
        data_egress=True, egress_type="cloud_metadata", network_behavior="read-only Slack API",
        path_scope_required=False, max_files_without_confirmation=None,
        max_total_bytes_without_confirmation=None, overwrite_policy="allow",
        secret_scan_required=False, requires_diff_preview=False,
        dry_run_supported=True, undo_supported=False, atomic=True,
        requires_screenshot=False, can_indirectly_execute_code=False,
        code_execution_mitigations=None, platforms=ALL_PLATFORMS,
        domain="slack", batchable=False, idempotent=True,
    ),
    # ── Trello tools ──────────────────────────────────────────────────────────
    ToolMetadata(
        name="trello_list_boards", description="List all Trello boards for the authenticated user.",
        risk_level=RiskLevel.LOW, reversible=True, reversible_notes=None,
        requires_confirmation=False, conditional_confirmation_rules=[],
        data_egress=True, egress_type="cloud_metadata", network_behavior="read-only Trello API",
        path_scope_required=False, max_files_without_confirmation=None,
        max_total_bytes_without_confirmation=None, overwrite_policy="allow",
        secret_scan_required=False, requires_diff_preview=False,
        dry_run_supported=True, undo_supported=False, atomic=True,
        requires_screenshot=False, can_indirectly_execute_code=False,
        code_execution_mitigations=None, platforms=ALL_PLATFORMS,
        domain="trello", batchable=False, idempotent=True,
    ),
    ToolMetadata(
        name="trello_list_cards", description="List all cards on a Trello board.",
        risk_level=RiskLevel.LOW, reversible=True, reversible_notes=None,
        requires_confirmation=False, conditional_confirmation_rules=[],
        data_egress=True, egress_type="cloud_content", network_behavior="read-only Trello API",
        path_scope_required=False, max_files_without_confirmation=None,
        max_total_bytes_without_confirmation=None, overwrite_policy="allow",
        secret_scan_required=False, requires_diff_preview=False,
        dry_run_supported=True, undo_supported=False, atomic=True,
        requires_screenshot=False, can_indirectly_execute_code=False,
        code_execution_mitigations=None, platforms=ALL_PLATFORMS,
        domain="trello", batchable=False, idempotent=True,
    ),
    ToolMetadata(
        name="trello_create_card", description="Create a new card on a Trello list.",
        risk_level=RiskLevel.MEDIUM, reversible=True, reversible_notes="Card can be deleted",
        requires_confirmation=False, conditional_confirmation_rules=[],
        data_egress=True, egress_type="cloud_content", network_behavior="write Trello API",
        path_scope_required=False, max_files_without_confirmation=None,
        max_total_bytes_without_confirmation=None, overwrite_policy="allow",
        secret_scan_required=False, requires_diff_preview=False,
        dry_run_supported=True, undo_supported=False, atomic=True,
        requires_screenshot=False, can_indirectly_execute_code=False,
        code_execution_mitigations=None, platforms=ALL_PLATFORMS,
        domain="trello", batchable=False, idempotent=False,
    ),
    ToolMetadata(
        name="trello_get_lists", description="Get all lists (columns) on a Trello board.",
        risk_level=RiskLevel.LOW, reversible=True, reversible_notes=None,
        requires_confirmation=False, conditional_confirmation_rules=[],
        data_egress=True, egress_type="cloud_metadata", network_behavior="read-only Trello API",
        path_scope_required=False, max_files_without_confirmation=None,
        max_total_bytes_without_confirmation=None, overwrite_policy="allow",
        secret_scan_required=False, requires_diff_preview=False,
        dry_run_supported=True, undo_supported=False, atomic=True,
        requires_screenshot=False, can_indirectly_execute_code=False,
        code_execution_mitigations=None, platforms=ALL_PLATFORMS,
        domain="trello", batchable=False, idempotent=True,
    ),
    # ── Spotify tools ─────────────────────────────────────────────────────────
    ToolMetadata(
        name="spotify_search", description="Search Spotify for tracks by name, artist, or album.",
        risk_level=RiskLevel.LOW, reversible=True, reversible_notes=None,
        requires_confirmation=False, conditional_confirmation_rules=[],
        data_egress=True, egress_type="cloud_metadata", network_behavior="read-only Spotify API",
        path_scope_required=False, max_files_without_confirmation=None,
        max_total_bytes_without_confirmation=None, overwrite_policy="allow",
        secret_scan_required=False, requires_diff_preview=False,
        dry_run_supported=True, undo_supported=False, atomic=True,
        requires_screenshot=False, can_indirectly_execute_code=False,
        code_execution_mitigations=None, platforms=ALL_PLATFORMS,
        domain="spotify", batchable=False, idempotent=True,
    ),
    ToolMetadata(
        name="spotify_current_track", description="Get the currently playing Spotify track.",
        risk_level=RiskLevel.LOW, reversible=True, reversible_notes=None,
        requires_confirmation=False, conditional_confirmation_rules=[],
        data_egress=True, egress_type="cloud_metadata", network_behavior="read-only Spotify API",
        path_scope_required=False, max_files_without_confirmation=None,
        max_total_bytes_without_confirmation=None, overwrite_policy="allow",
        secret_scan_required=False, requires_diff_preview=False,
        dry_run_supported=True, undo_supported=False, atomic=True,
        requires_screenshot=False, can_indirectly_execute_code=False,
        code_execution_mitigations=None, platforms=ALL_PLATFORMS,
        domain="spotify", batchable=False, idempotent=True,
    ),
    ToolMetadata(
        name="spotify_play_pause", description="Play or pause Spotify playback.",
        risk_level=RiskLevel.LOW, reversible=True, reversible_notes=None,
        requires_confirmation=False, conditional_confirmation_rules=[],
        data_egress=False, egress_type="none", network_behavior="write Spotify player API",
        path_scope_required=False, max_files_without_confirmation=None,
        max_total_bytes_without_confirmation=None, overwrite_policy="allow",
        secret_scan_required=False, requires_diff_preview=False,
        dry_run_supported=True, undo_supported=False, atomic=True,
        requires_screenshot=False, can_indirectly_execute_code=False,
        code_execution_mitigations=None, platforms=ALL_PLATFORMS,
        domain="spotify", batchable=False, idempotent=False,
    ),
    # ── YouTube tools ─────────────────────────────────────────────────────────
    ToolMetadata(
        name="youtube_search", description="Search YouTube for videos by keyword.",
        risk_level=RiskLevel.LOW, reversible=True, reversible_notes=None,
        requires_confirmation=False, conditional_confirmation_rules=[],
        data_egress=True, egress_type="cloud_metadata", network_behavior="read-only YouTube API",
        path_scope_required=False, max_files_without_confirmation=None,
        max_total_bytes_without_confirmation=None, overwrite_policy="allow",
        secret_scan_required=False, requires_diff_preview=False,
        dry_run_supported=True, undo_supported=False, atomic=True,
        requires_screenshot=False, can_indirectly_execute_code=False,
        code_execution_mitigations=None, platforms=ALL_PLATFORMS,
        domain="youtube", batchable=False, idempotent=True,
    ),
    ToolMetadata(
        name="youtube_get_video", description="Get detailed info about a YouTube video.",
        risk_level=RiskLevel.LOW, reversible=True, reversible_notes=None,
        requires_confirmation=False, conditional_confirmation_rules=[],
        data_egress=True, egress_type="cloud_content", network_behavior="read-only YouTube API",
        path_scope_required=False, max_files_without_confirmation=None,
        max_total_bytes_without_confirmation=None, overwrite_policy="allow",
        secret_scan_required=False, requires_diff_preview=False,
        dry_run_supported=True, undo_supported=False, atomic=True,
        requires_screenshot=False, can_indirectly_execute_code=False,
        code_execution_mitigations=None, platforms=ALL_PLATFORMS,
        domain="youtube", batchable=False, idempotent=True,
    ),
    ToolMetadata(
        name="youtube_search_channels", description="Search YouTube for channels by name.",
        risk_level=RiskLevel.LOW, reversible=True, reversible_notes=None,
        requires_confirmation=False, conditional_confirmation_rules=[],
        data_egress=True, egress_type="cloud_metadata", network_behavior="read-only YouTube API",
        path_scope_required=False, max_files_without_confirmation=None,
        max_total_bytes_without_confirmation=None, overwrite_policy="allow",
        secret_scan_required=False, requires_diff_preview=False,
        dry_run_supported=True, undo_supported=False, atomic=True,
        requires_screenshot=False, can_indirectly_execute_code=False,
        code_execution_mitigations=None, platforms=ALL_PLATFORMS,
        domain="youtube", batchable=False, idempotent=True,
    ),
]

TOOL_REGISTRY: dict[str, ToolMetadata] = {t.name: t for t in _REGISTRY_DATA}

_POLICY_VERSION = hashlib.sha256(
    json.dumps(
        {name: meta.risk_level.value for name, meta in TOOL_REGISTRY.items()},
        sort_keys=True
    ).encode()
).hexdigest()[:16]


def get_tool(name: str) -> ToolMetadata | None:
    return TOOL_REGISTRY.get(name)


def list_tools() -> list[str]:
    return sorted(TOOL_REGISTRY.keys())


def policy_version() -> str:
    return _POLICY_VERSION
